/// Create Project Screen
/// 
/// Screen for PM to create a new project with member selection.

import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../core/theme/app_colors.dart';
import '../../../domain/entities/project.dart';
import '../../../domain/entities/user.dart';
import '../../../domain/entities/chat_room.dart';
import '../../../data/datasources/project_datasource.dart';
import '../../../data/datasources/user_datasource.dart';
import '../../../data/datasources/chat_datasource.dart';
import '../../blocs/blocs.dart';

class CreateProjectScreen extends StatefulWidget {
  const CreateProjectScreen({super.key});

  @override
  State<CreateProjectScreen> createState() => _CreateProjectScreenState();
}

class _CreateProjectScreenState extends State<CreateProjectScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _memberSearchController = TextEditingController();
  
  DateTime? _startDate;
  DateTime? _endDate;
  ProjectStatus _status = ProjectStatus.planning;
  bool _isLoading = false;
  
  // Members
  List<User> _selectedMembers = [];
  List<User> _searchResults = [];
  bool _isSearching = false;

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    _memberSearchController.dispose();
    super.dispose();
  }

  Future<void> _searchUsers(String query) async {
    if (query.trim().isEmpty) {
      setState(() {
        _searchResults = [];
        _isSearching = false;
      });
      return;
    }

    setState(() => _isSearching = true);

    try {
      final datasource = UserDataSourceImpl();
      final results = await datasource.searchUsers(query);
      
      // Filter out already selected members and current user
      final authState = context.read<AuthBloc>().state;
      final currentUserId = authState.user?.id ?? '';
      
      if (mounted) {
        setState(() {
          _searchResults = results
              .map((m) => m.toEntity())
              .where((u) => u.id != currentUserId && !_selectedMembers.any((m) => m.id == u.id))
              .toList();
          _isSearching = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _searchResults = [];
          _isSearching = false;
        });
      }
    }
  }

  void _addMember(User user) {
    setState(() {
      _selectedMembers.add(user);
      _searchResults = [];
      _memberSearchController.clear();
    });
  }

  void _removeMember(User user) {
    setState(() {
      _selectedMembers.removeWhere((m) => m.id == user.id);
    });
  }

  Future<void> _selectDate(bool isStart) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: isStart ? (_startDate ?? DateTime.now()) : (_endDate ?? DateTime.now().add(const Duration(days: 30))),
      firstDate: DateTime.now().subtract(const Duration(days: 365)),
      lastDate: DateTime.now().add(const Duration(days: 365 * 3)),
      locale: const Locale('vi', 'VN'),
    );
    
    if (picked != null) {
      setState(() {
        if (isStart) {
          _startDate = picked;
        } else {
          _endDate = picked;
        }
      });
    }
  }

  Future<void> _createProject() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final authState = context.read<AuthBloc>().state;
      final userId = authState.user?.id ?? '';

      // Collect all member IDs (owner + selected members)
      final memberIds = [userId, ..._selectedMembers.map((m) => m.id)];

      final project = Project(
        id: '', // Will be generated by Firestore
        name: _nameController.text.trim(),
        description: _descriptionController.text.trim(),
        status: _status,
        ownerId: userId,
        startDate: _startDate,
        endDate: _endDate,
        progress: 0,
        memberIds: memberIds,
      );

      final projectDatasource = ProjectDataSourceImpl();
      final createdProject = await projectDatasource.createProject(project);

      // Auto-create a group chat room for the project
      final chatRoom = ChatRoom(
        id: '', // Will be generated by Firestore
        name: _nameController.text.trim(), // Same name as project
        type: ChatRoomType.group,
        memberIds: memberIds,
        createdBy: userId,
        createdAt: DateTime.now(),
        lastMessage: 'Phòng chat dự án đã được tạo',
        lastMessageSenderId: userId,
        lastMessageTime: DateTime.now(),
      );

      final chatDatasource = ChatDataSourceImpl();
      await chatDatasource.createChatRoom(chatRoom);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('Tạo dự án và phòng chat thành công!'),
            backgroundColor: AppColors.success,
          ),
        );
        context.pop(true); // Return true to indicate success
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Lỗi: ${e.toString()}'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Tạo dự án mới'),
        actions: [
          TextButton(
            onPressed: _isLoading ? null : _createProject,
            child: _isLoading
                ? SizedBox(
                    width: 20.w,
                    height: 20.w,
                    child: const CircularProgressIndicator(
                      strokeWidth: 2,
                      color: Colors.white,
                    ),
                  )
                : const Text('Lưu', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
          ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: EdgeInsets.all(16.w),
          children: [
            // Project Name
            Text('Tên dự án *', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
            SizedBox(height: 8.h),
            TextFormField(
              controller: _nameController,
              decoration: InputDecoration(
                hintText: 'Nhập tên dự án',
                prefixIcon: const Icon(Icons.folder),
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Vui lòng nhập tên dự án';
                }
                return null;
              },
            ),
            SizedBox(height: 20.h),

            // Description
            Text('Mô tả', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
            SizedBox(height: 8.h),
            TextFormField(
              controller: _descriptionController,
              maxLines: 3,
              decoration: InputDecoration(
                hintText: 'Mô tả dự án (không bắt buộc)',
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                alignLabelWithHint: true,
              ),
            ),
            SizedBox(height: 20.h),

            // Members Section
            Text('Thành viên', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
            SizedBox(height: 8.h),
            
            // Selected members chips
            if (_selectedMembers.isNotEmpty) ...[
              Wrap(
                spacing: 8.w,
                runSpacing: 8.h,
                children: _selectedMembers.map((member) => Chip(
                  avatar: CircleAvatar(
                    backgroundColor: AppColors.primary,
                    child: Text(
                      (member.displayName ?? member.email)[0].toUpperCase(),
                      style: const TextStyle(color: Colors.white, fontSize: 12),
                    ),
                  ),
                  label: Text(member.displayName ?? member.email),
                  deleteIcon: const Icon(Icons.close, size: 18),
                  onDeleted: () => _removeMember(member),
                )).toList(),
              ),
              SizedBox(height: 12.h),
            ],
            
            // Search field
            TextField(
              controller: _memberSearchController,
              decoration: InputDecoration(
                hintText: 'Tìm kiếm theo tên hoặc email...',
                prefixIcon: const Icon(Icons.person_add),
                suffixIcon: _isSearching 
                    ? Padding(
                        padding: EdgeInsets.all(12.w),
                        child: SizedBox(width: 20.w, height: 20.w, child: const CircularProgressIndicator(strokeWidth: 2)),
                      )
                    : null,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
              ),
              onChanged: (value) => _searchUsers(value),
            ),
            
            // Search results
            if (_searchResults.isNotEmpty)
              Container(
                margin: EdgeInsets.only(top: 4.h),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12.r),
                  border: Border.all(color: AppColors.border),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withValues(alpha: 0.1),
                      blurRadius: 8,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Column(
                  children: _searchResults.take(5).map((user) => ListTile(
                    leading: CircleAvatar(
                      backgroundColor: AppColors.primary.withValues(alpha: 0.1),
                      child: Text(
                        (user.displayName ?? user.email)[0].toUpperCase(),
                        style: TextStyle(color: AppColors.primary, fontWeight: FontWeight.bold),
                      ),
                    ),
                    title: Text(user.displayName ?? 'No name'),
                    subtitle: Text(user.email, style: TextStyle(fontSize: 12.sp)),
                    trailing: Icon(Icons.add_circle, color: AppColors.primary),
                    onTap: () => _addMember(user),
                  )).toList(),
                ),
              ),
            
            SizedBox(height: 20.h),

            // Status
            Text('Trạng thái', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
            SizedBox(height: 8.h),
            DropdownButtonFormField<ProjectStatus>(
              value: _status,
              decoration: InputDecoration(
                prefixIcon: const Icon(Icons.flag),
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
              ),
              items: ProjectStatus.values.map((status) {
                return DropdownMenuItem(
                  value: status,
                  child: Text(status.displayName),
                );
              }).toList(),
              onChanged: (value) {
                if (value != null) {
                  setState(() => _status = value);
                }
              },
            ),
            SizedBox(height: 20.h),

            // Dates Row
            Row(
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Ngày bắt đầu', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
                      SizedBox(height: 8.h),
                      InkWell(
                        onTap: () => _selectDate(true),
                        child: Container(
                          padding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 16.h),
                          decoration: BoxDecoration(
                            border: Border.all(color: AppColors.border),
                            borderRadius: BorderRadius.circular(12.r),
                          ),
                          child: Row(
                            children: [
                              Icon(Icons.calendar_today, size: 20.w, color: AppColors.textSecondary),
                              SizedBox(width: 8.w),
                              Text(
                                _startDate != null
                                    ? DateFormat('dd/MM/yyyy').format(_startDate!)
                                    : 'Chọn ngày',
                                style: TextStyle(
                                  color: _startDate != null ? AppColors.textPrimary : AppColors.textHint,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                SizedBox(width: 12.w),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Ngày kết thúc', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
                      SizedBox(height: 8.h),
                      InkWell(
                        onTap: () => _selectDate(false),
                        child: Container(
                          padding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 16.h),
                          decoration: BoxDecoration(
                            border: Border.all(color: AppColors.border),
                            borderRadius: BorderRadius.circular(12.r),
                          ),
                          child: Row(
                            children: [
                              Icon(Icons.event, size: 20.w, color: AppColors.textSecondary),
                              SizedBox(width: 8.w),
                              Text(
                                _endDate != null
                                    ? DateFormat('dd/MM/yyyy').format(_endDate!)
                                    : 'Chọn ngày',
                                style: TextStyle(
                                  color: _endDate != null ? AppColors.textPrimary : AppColors.textHint,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            SizedBox(height: 32.h),

            // Submit Button
            SizedBox(
              width: double.infinity,
              height: 54.h,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _createProject,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primary,
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
                ),
                child: _isLoading
                    ? const CircularProgressIndicator(color: Colors.white)
                    : Text('Tạo dự án', style: TextStyle(fontSize: 16.sp, fontWeight: FontWeight.bold)),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
