/// Create Task Screen
/// 
/// Screen for PM to create a new task/issue.

import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../../core/theme/app_colors.dart';
import '../../../domain/entities/issue.dart';
import '../../../domain/entities/project.dart';
import '../../../data/datasources/issue_datasource.dart';
import '../../../data/datasources/project_datasource.dart';
import '../../blocs/blocs.dart';

class CreateTaskScreen extends StatefulWidget {
  final String? projectId; // Optional - if provided, pre-select project

  const CreateTaskScreen({super.key, this.projectId});

  @override
  State<CreateTaskScreen> createState() => _CreateTaskScreenState();
}

class _CreateTaskScreenState extends State<CreateTaskScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  
  String? _selectedProjectId;
  IssueType _type = IssueType.task;
  IssuePriority _priority = IssuePriority.medium;
  DateTime? _dueDate;
  bool _isLoading = false;
  List<Project> _projects = [];
  bool _loadingProjects = true;

  @override
  void initState() {
    super.initState();
    _selectedProjectId = widget.projectId;
    _loadProjects();
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  Future<void> _loadProjects() async {
    try {
      final datasource = ProjectDataSourceImpl();
      final projects = await datasource.getProjects();
      if (mounted) {
        setState(() {
          _projects = projects.map((m) => m.toEntity()).toList();
          _loadingProjects = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _loadingProjects = false);
      }
    }
  }

  Future<void> _selectDueDate() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _dueDate ?? DateTime.now().add(const Duration(days: 7)),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365 * 2)),
      locale: const Locale('vi', 'VN'),
    );
    
    if (picked != null) {
      setState(() => _dueDate = picked);
    }
  }

  Future<void> _createTask() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedProjectId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Vui lòng chọn dự án'), backgroundColor: Colors.orange),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final authState = context.read<AuthBloc>().state;
      final userId = authState.user?.id ?? '';

      final issue = Issue(
        id: '', // Will be generated by Firestore
        projectId: _selectedProjectId!,
        title: _titleController.text.trim(),
        description: _descriptionController.text.trim().isEmpty 
            ? null 
            : _descriptionController.text.trim(),
        type: _type,
        priority: _priority,
        status: IssueStatus.todo,
        reporterId: userId,
        dueDate: _dueDate,
      );

      final datasource = IssueDataSourceImpl();
      await datasource.createIssue(issue);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('Tạo tác vụ thành công!'),
            backgroundColor: AppColors.success,
          ),
        );
        context.pop(true); // Return true to indicate success
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Lỗi: ${e.toString()}'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Tạo tác vụ mới'),
        actions: [
          TextButton(
            onPressed: _isLoading ? null : _createTask,
            child: _isLoading
                ? SizedBox(
                    width: 20.w,
                    height: 20.w,
                    child: const CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                  )
                : const Text('Lưu', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
          ),
        ],
      ),
      body: Form(
        key: _formKey,
        child: ListView(
          padding: EdgeInsets.all(16.w),
          children: [
            // Project Selection
            Text('Dự án *', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
            SizedBox(height: 8.h),
            _loadingProjects
                ? const Center(child: CircularProgressIndicator())
                : DropdownButtonFormField<String>(
                    value: _selectedProjectId,
                    decoration: InputDecoration(
                      prefixIcon: const Icon(Icons.folder),
                      hintText: 'Chọn dự án',
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                    ),
                    items: _projects.map((project) {
                      return DropdownMenuItem(
                        value: project.id,
                        child: Text(project.name, overflow: TextOverflow.ellipsis),
                      );
                    }).toList(),
                    onChanged: (value) => setState(() => _selectedProjectId = value),
                    validator: (value) => value == null ? 'Vui lòng chọn dự án' : null,
                  ),
            SizedBox(height: 20.h),

            // Task Title
            Text('Tiêu đề *', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
            SizedBox(height: 8.h),
            TextFormField(
              controller: _titleController,
              decoration: InputDecoration(
                hintText: 'Nhập tiêu đề tác vụ',
                prefixIcon: const Icon(Icons.assignment),
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
              ),
              validator: (value) {
                if (value == null || value.trim().isEmpty) {
                  return 'Vui lòng nhập tiêu đề';
                }
                return null;
              },
            ),
            SizedBox(height: 20.h),

            // Description
            Text('Mô tả', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
            SizedBox(height: 8.h),
            TextFormField(
              controller: _descriptionController,
              maxLines: 3,
              decoration: InputDecoration(
                hintText: 'Mô tả chi tiết (không bắt buộc)',
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                alignLabelWithHint: true,
              ),
            ),
            SizedBox(height: 20.h),

            // Type and Priority Row
            Row(
              children: [
                // Type
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Loại', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
                      SizedBox(height: 8.h),
                      DropdownButtonFormField<IssueType>(
                        value: _type,
                        decoration: InputDecoration(
                          contentPadding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 12.h),
                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                        ),
                        items: IssueType.values.map((type) {
                          return DropdownMenuItem(
                            value: type,
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Icon(_getTypeIcon(type), size: 18.w, color: _getTypeColor(type)),
                                SizedBox(width: 8.w),
                                Text(type.displayName),
                              ],
                            ),
                          );
                        }).toList(),
                        onChanged: (value) {
                          if (value != null) setState(() => _type = value);
                        },
                      ),
                    ],
                  ),
                ),
                SizedBox(width: 12.w),
                // Priority
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Độ ưu tiên', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
                      SizedBox(height: 8.h),
                      DropdownButtonFormField<IssuePriority>(
                        value: _priority,
                        decoration: InputDecoration(
                          contentPadding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 12.h),
                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
                        ),
                        items: IssuePriority.values.map((priority) {
                          return DropdownMenuItem(
                            value: priority,
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                Icon(Icons.flag, size: 18.w, color: _getPriorityColor(priority)),
                                SizedBox(width: 8.w),
                                Text(priority.displayName),
                              ],
                            ),
                          );
                        }).toList(),
                        onChanged: (value) {
                          if (value != null) setState(() => _priority = value);
                        },
                      ),
                    ],
                  ),
                ),
              ],
            ),
            SizedBox(height: 20.h),

            // Due Date
            Text('Hạn hoàn thành', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14.sp)),
            SizedBox(height: 8.h),
            InkWell(
              onTap: _selectDueDate,
              child: Container(
                padding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 16.h),
                decoration: BoxDecoration(
                  border: Border.all(color: AppColors.border),
                  borderRadius: BorderRadius.circular(12.r),
                ),
                child: Row(
                  children: [
                    Icon(Icons.event, size: 22.w, color: AppColors.textSecondary),
                    SizedBox(width: 12.w),
                    Text(
                      _dueDate != null
                          ? DateFormat('dd/MM/yyyy').format(_dueDate!)
                          : 'Chọn ngày (không bắt buộc)',
                      style: TextStyle(
                        fontSize: 16.sp,
                        color: _dueDate != null ? AppColors.textPrimary : AppColors.textHint,
                      ),
                    ),
                    const Spacer(),
                    if (_dueDate != null)
                      IconButton(
                        icon: Icon(Icons.clear, size: 20.w),
                        onPressed: () => setState(() => _dueDate = null),
                        padding: EdgeInsets.zero,
                        constraints: const BoxConstraints(),
                      ),
                  ],
                ),
              ),
            ),
            SizedBox(height: 32.h),

            // Submit Button
            SizedBox(
              width: double.infinity,
              height: 54.h,
              child: ElevatedButton(
                onPressed: _isLoading ? null : _createTask,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primary,
                  foregroundColor: Colors.white,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
                ),
                child: _isLoading
                    ? const CircularProgressIndicator(color: Colors.white)
                    : Text('Tạo tác vụ', style: TextStyle(fontSize: 16.sp, fontWeight: FontWeight.bold)),
              ),
            ),
          ],
        ),
      ),
    );
  }

  IconData _getTypeIcon(IssueType type) {
    switch (type) {
      case IssueType.task: return Icons.check_circle_outline;
      case IssueType.bug: return Icons.bug_report;
      case IssueType.story: return Icons.bookmark;
    }
  }

  Color _getTypeColor(IssueType type) {
    switch (type) {
      case IssueType.task: return AppColors.primary;
      case IssueType.bug: return AppColors.error;
      case IssueType.story: return AppColors.success;
    }
  }

  Color _getPriorityColor(IssuePriority priority) {
    switch (priority) {
      case IssuePriority.low: return AppColors.success;
      case IssuePriority.medium: return AppColors.warning;
      case IssuePriority.high: return Colors.orange;
      case IssuePriority.critical: return AppColors.error;
    }
  }
}
