// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwSq8gecMgrlu-U1-Dpjfkdwq6-VRxI-8',
    appId: '1:435645589778:web:a8ccd854ba43653eea6bcb',
    messagingSenderId: '435645589778',
    projectId: 'du-an-mobile-2025',
    authDomain: 'du-an-mobile-2025.firebaseapp.com',
    storageBucket: 'du-an-mobile-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJYUYnMsbZ8R14z2D9PPv9nNAd_9UaceM',
    appId: '1:435645589778:android:ce0db19fe4916d83ea6bcb',
    messagingSenderId: '435645589778',
    projectId: 'du-an-mobile-2025',
    storageBucket: 'du-an-mobile-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQBdwGkI7_-ErcsF_4CTmVD9-ZrHznChk',
    appId: '1:435645589778:ios:b15775ba882ab89cea6bcb',
    messagingSenderId: '435645589778',
    projectId: 'du-an-mobile-2025',
    storageBucket: 'du-an-mobile-2025.firebasestorage.app',
    iosBundleId: 'com.ems.enterpriseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQBdwGkI7_-ErcsF_4CTmVD9-ZrHznChk',
    appId: '1:435645589778:ios:b15775ba882ab89cea6bcb',
    messagingSenderId: '435645589778',
    projectId: 'du-an-mobile-2025',
    storageBucket: 'du-an-mobile-2025.firebasestorage.app',
    iosBundleId: 'com.ems.enterpriseMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwSq8gecMgrlu-U1-Dpjfkdwq6-VRxI-8',
    appId: '1:435645589778:web:8b509bf4b2097bf0ea6bcb',
    messagingSenderId: '435645589778',
    projectId: 'du-an-mobile-2025',
    authDomain: 'du-an-mobile-2025.firebaseapp.com',
    storageBucket: 'du-an-mobile-2025.firebasestorage.app',
  );
}
