// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8nP_xe4YWShXaB8QRSmOBjaxtfEQY7g',
    appId: '1:102252090452:web:044717666c9b6df67949c1',
    messagingSenderId: '102252090452',
    projectId: 'du-an-mobile-2025-v2',
    authDomain: 'du-an-mobile-2025-v2.firebaseapp.com',
    storageBucket: 'du-an-mobile-2025-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7i2-4DVFN1QvdnN7mKBbhzeNj_N42i98',
    appId: '1:102252090452:android:405e3ca085be9b467949c1',
    messagingSenderId: '102252090452',
    projectId: 'du-an-mobile-2025-v2',
    storageBucket: 'du-an-mobile-2025-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4xMpQ_aaxYLUGabrHyIxHYIVNvFA3Pus',
    appId: '1:102252090452:ios:e9bf9266ea0358c47949c1',
    messagingSenderId: '102252090452',
    projectId: 'du-an-mobile-2025-v2',
    storageBucket: 'du-an-mobile-2025-v2.firebasestorage.app',
    iosBundleId: 'com.ems.enterpriseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4xMpQ_aaxYLUGabrHyIxHYIVNvFA3Pus',
    appId: '1:102252090452:ios:e9bf9266ea0358c47949c1',
    messagingSenderId: '102252090452',
    projectId: 'du-an-mobile-2025-v2',
    storageBucket: 'du-an-mobile-2025-v2.firebasestorage.app',
    iosBundleId: 'com.ems.enterpriseMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb8nP_xe4YWShXaB8QRSmOBjaxtfEQY7g',
    appId: '1:102252090452:web:4542744ba39b65767949c1',
    messagingSenderId: '102252090452',
    projectId: 'du-an-mobile-2025-v2',
    authDomain: 'du-an-mobile-2025-v2.firebaseapp.com',
    storageBucket: 'du-an-mobile-2025-v2.firebasestorage.app',
  );

}